import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
import {install} from '../bin/install.mjs';
import {navigate} from '../skills/reversa-analysis/scripts/lib/navigation.mjs';
import {validate} from '../skills/reversa-analysis/scripts/lib/validate.mjs';
import {impact,inspect} from '../skills/reversa-analysis/scripts/lib/sources.mjs';
import {json,writeJson,safePath,sha256,within} from '../skills/reversa-analysis/scripts/lib/io.mjs';
import {withoutGenerated} from '../skills/reversa-analysis/scripts/lib/markdown.mjs';
const suite=fileURLToPath(new URL('../',import.meta.url)),example=path.join(suite,'examples/library-lending');
const tempBase=fs.realpathSync(os.tmpdir());
function sandbox(t){const dir=fs.mkdtempSync(path.join(tempBase,'rsa-test-'));t.after(()=>{const resolved=fs.realpathSync(dir);assert.ok(within(tempBase,resolved)&&path.basename(resolved).startsWith('rsa-test-'));fs.rmSync(resolved,{recursive:true});});return dir;}
function copy(t){const dir=sandbox(t);fs.cpSync(example,dir,{recursive:true});return dir;}
function alter(dir,file,fn){writeJson(dir,file,fn(json(path.join(dir,file))));}
function fail(result,code){assert.equal(result.ok,false);assert.ok(result.errors.some(e=>e.code===code),JSON.stringify(result));}
const cli=(...a)=>spawnSync(process.execPath,[path.join(suite,'bin/analysis.mjs'),...a],{encoding:'utf8'});

test('учебный пакет проходит проверку, FR и Mermaid учитываются',()=>{const r=validate(example,{strict:true});assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.traceRequirements,3);assert.equal(r.mermaid.blocks,5);assert.equal(r.mermaid.syntax,'not_checked');});
test('инициализация создаёт честный черновик и не перезаписывает существующий пакет',t=>{const dir=path.join(sandbox(t),'Русская папка');let r=cli('init','--output',dir,'--system','Тестовая система');assert.equal(r.status,0,r.stderr);assert.equal(validate(dir).ok,true);assert.equal(json(path.join(dir,'catalog.json')).documents[0].status,'draft');const before=fs.readFileSync(path.join(dir,'README.md'));r=cli('init','--output',dir,'--system','Другая');assert.equal(r.status,1);assert.deepEqual(fs.readFileSync(path.join(dir,'README.md')),before);});
test('nav идемпотентен и сохраняет ручной текст и собственные якоря',t=>{const dir=copy(t),file=path.join(dir,'rules.md');fs.appendFileSync(file,'\nРучное уточнение: значение 17 не относится к сроку.\n');const before=withoutGenerated(fs.readFileSync(file,'utf8')).trim();const ev=fs.readFileSync(path.join(dir,'evidence.json'));navigate(dir,{write:true});assert.equal(withoutGenerated(fs.readFileSync(file,'utf8')).trim(),before);assert.deepEqual(navigate(dir,{write:true}).changed,[]);assert.ok(fs.readFileSync(file,'utf8').includes('id="br-001"'));assert.deepEqual(fs.readFileSync(path.join(dir,'evidence.json')),ev);});
test('nav предварительно проверяет все страницы до записи',t=>{const dir=copy(t);const original=fs.readFileSync(path.join(dir,'README.md'));alter(dir,'catalog.json',c=>{c.documents.at(-1).parent='MISSING-001';return c;});assert.throws(()=>navigate(dir,{write:true}));assert.deepEqual(fs.readFileSync(path.join(dir,'README.md')),original);});
test('nav без --write не меняет файлы',t=>{const dir=copy(t);fs.appendFileSync(path.join(dir,'README.md'),'\n## Новый раздел\n\nАвторский текст.\n');const before=fs.readFileSync(path.join(dir,'README.md'));assert.ok(navigate(dir).changed.length);assert.deepEqual(fs.readFileSync(path.join(dir,'README.md')),before);});
test('nav отклоняет перепутанные маркеры без потери содержимого',t=>{const dir=copy(t),file=path.join(dir,'README.md');let body=fs.readFileSync(file,'utf8');body=body.replace('<!-- rsa:nav:start -->','TEMP').replace('<!-- rsa:nav:end -->','<!-- rsa:nav:start -->').replace('TEMP','<!-- rsa:nav:end -->');fs.writeFileSync(file,body);assert.throws(()=>navigate(dir,{write:true}));assert.equal(fs.readFileSync(file,'utf8'),body);});
test('сломанный якорь трассируемости обнаруживается',t=>{const dir=copy(t);alter(dir,'traceability.json',x=>{x.requirements[0].acceptanceRefs[0].anchor='missing';return x;});fail(validate(dir),'TRACE_ANCHOR');});
test('неизвестность без вопроса не проходит как установленное правило',t=>{const dir=copy(t);alter(dir,'evidence.json',e=>{e.claims[0].basis='unknown';return e;});fail(validate(dir),'MISSING_QUESTION');});
test('согласование без основания и с непроверенными claims отклоняется',t=>{const dir=copy(t);alter(dir,'catalog.json',c=>{c.documents[0].status='approved';return c;});const r=validate(dir);fail(r,'APPROVAL');fail(r,'UNREVIEWED_CLAIMS');});
test('повторные ID, цикл и выход пути выявляются',t=>{const dir=copy(t);alter(dir,'catalog.json',c=>{c.documents[1].id=c.documents[0].id;c.documents[0].parent=c.documents[0].id;c.documents[2].path='../escape.md';return c;});const r=validate(dir);fail(r,'DUPLICATE_ID');fail(r,'CYCLE');fail(r,'DOCUMENT_FILE');});
test('повреждённые типы реестров дают отчёт об ошибке',t=>{const dir=copy(t);alter(dir,'evidence.json',e=>{e.claims[0].sourceIds='SRC-001';e.questions[0].documentIds=null;return e;});fail(validate(dir),'REFERENCES');});
test('ссылки через определения проверяются, содержимое кода пропускается',t=>{const dir=copy(t);fs.appendFileSync(path.join(dir,'README.md'),'\n[Проверка][ref]\n\n[ref]: missing.md\n\n```text\n[Не ссылка](another-missing.md)\n```\n');const r=validate(dir);fail(r,'LINK');assert.equal(r.errors.filter(e=>e.code==='LINK').length,1);});
test('вложения вне пакета и отсутствующие файлы отклоняются',t=>{const dir=copy(t);alter(dir,'catalog.json',c=>{c.attachments.push({path:'../outside.txt',purpose:'bad'},{path:'missing.txt',purpose:'bad'});return c;});assert.equal(validate(dir).errors.filter(e=>e.code==='ATTACHMENT').length,2);});
test('установка во все три формата идемпотентна, preview ничего не создаёт',t=>{const dir=sandbox(t);const p=install(dir,{agent:'all'});assert.equal(p.targets.length,3);assert.deepEqual(fs.readdirSync(dir),[]);install(dir,{agent:'all',apply:true});for(const folder of ['.agents','.claude','.qwen'])assert.ok(fs.existsSync(path.join(dir,folder,'skills/reversa-analysis-spec/SKILL.md')));const again=install(dir,{agent:'all',apply:true});assert.ok(again.targets.every(x=>x.create===0&&x.update===0));assert.ok(!fs.existsSync(path.join(dir,'AGENTS.md')));});
test('конфликт установки не меняет ни один целевой каталог',t=>{const dir=sandbox(t),file=path.join(dir,'.agents/skills/reversa-analysis/SKILL.md');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,'Личный навык');assert.throws(()=>install(dir,{agent:'all',apply:true}));assert.equal(fs.readFileSync(file,'utf8'),'Личный навык');assert.ok(!fs.existsSync(path.join(dir,'.claude')));});
test('обновление не перезаписывает ручную правку',t=>{const dir=sandbox(t);install(dir,{agent:'qwen',apply:true});const file=path.join(dir,'.qwen/skills/reversa-analysis/SKILL.md');fs.appendFileSync(file,'\nРучное изменение.\n');const before=fs.readFileSync(file);assert.throws(()=>install(dir,{agent:'qwen',apply:true,update:true}));assert.deepEqual(fs.readFileSync(file),before);});
test('обновление разрешено для неизменённой зарегистрированной старой версии',t=>{const dir=sandbox(t);install(dir,{agent:'codex',apply:true});const rel='reversa-analysis/SKILL.md',file=path.join(dir,'.agents/skills',rel);fs.writeFileSync(file,'Предыдущая версия');alter(dir,'.agents/skills/.reversa-analysis-install.json',m=>{m.files[rel]=sha256(fs.readFileSync(file));return m;});const r=install(dir,{agent:'codex',apply:true,update:true});assert.equal(r.targets[0].update,1);assert.deepEqual(fs.readFileSync(file),fs.readFileSync(path.join(suite,'skills',rel)));});
test('установленный помощник работает из другого cwd и пути с пробелами',t=>{const dir=path.join(sandbox(t),'Проект с пробелами');fs.mkdirSync(dir);install(dir,{agent:'claude',apply:true});const script=path.join(dir,'.claude/skills/reversa-analysis/scripts/cli.mjs');const r=spawnSync(process.execPath,[script,'validate','--package',example],{cwd:os.tmpdir(),encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).ok,true);});
test('impact не меняет baseline и раскрывает связанные требования',t=>{const dir=copy(t);const before=fs.readFileSync(path.join(dir,'evidence.json'));assert.ok(impact(dir).sources.every(s=>s.state==='unchanged'));fs.appendFileSync(path.join(dir,'sources/policy.md'),'\nНовая редакция источника.\n');const report=impact(dir);assert.equal(report.sources[0].state,'changed');assert.equal(report.requirements.length,3);assert.ok(report.reviewDocuments.some(d=>d.id==='REQ-002'));assert.deepEqual(fs.readFileSync(path.join(dir,'evidence.json')),before);});
test('impact различает недоступный и удалённый как непроверенный источник',t=>{const dir=copy(t);alter(dir,'evidence.json',e=>{e.sources[0].locator='sources/missing.md';return e;});assert.equal(impact(dir).sources[0].state,'unavailable');});
test('inspect учитывает пользовательскую папку Reversa и не обходит выход за корень',t=>{const dir=sandbox(t);fs.mkdirSync(path.join(dir,'.reversa'));writeJson(dir,'.reversa/state.json',{output_folder:'custom'});fs.mkdirSync(path.join(dir,'custom'));fs.writeFileSync(path.join(dir,'custom/domain.md'),'Модель');let r=inspect(dir);assert.ok(r.files.some(f=>f.path==='custom/domain.md'));writeJson(dir,'.reversa/state.json',{output_folder:'../outside'});r=inspect(dir);assert.ok(r.warnings.some(w=>w.includes('выходит')));});
test('ограничитель путей отвергает абсолютные и родительские пути',t=>{const dir=sandbox(t);for(const p of ['../a','C:/a','/a','a\\b'])assert.throws(()=>safePath(dir,p));});
test('inspect не принимает собственный пакет аналитики за новый источник Reversa',t=>{const dir=sandbox(t),dest=path.join(dir,'_reversa_sdd','reader-docs');fs.cpSync(example,dest,{recursive:true});const report=inspect(dir);assert.ok(report.warnings.some(w=>w.includes('уже собранный')));assert.equal(report.files.length,0);});
test('календарные примеры имеют заявленные результаты',()=>{for(const [start,end]of [['2026-08-01','2026-08-15'],['2026-08-25','2026-09-08']]){const d=new Date(start+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+14);assert.equal(d.toISOString().slice(0,10),end);}});
